apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
      env: dev
      type: backend
  template:
    metadata:
      labels:
        app: web-app
        env: dev
        type: backend
    spec:
      containers:
        - name: nginx
          image: test/nginx:0.1.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
        - name: php-fpm
          image: test/php-fpm:0.1.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
        - name: redis
          image: redis:4-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379